version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:lts

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      # Check formatting
      - run:
          name: Check formatting
          command: npm run check

      # Run tests
      - run:
          name: Run tests
          command: npm test -- --ci --coverage --no-cache
          environment:
            JEST_JUNIT_OUTPUT: "./test-results/jest/results.xml"

      # Publish test results
      - store_test_results:
          path: test-results

      # Publish test coverage as artifact
      - store_artifacts:
          path: coverage
          destination: coverage

      # Compile TypeScript
      - run:
          name: Build
          command: npm run build

      # Publish JavaScript artifacts
      - store_artifacts:
          path: dist
          destination: dist
